### ISSUE TITLE
Missing parenthesis

### ISSUE THREAD

**Issue by MichaelTopple** [anttivs/serialmorse#1]
Hello,
Sorry to be a pain: this is my first time.
I've tried downloading and compiling this brilliant script to practice my CW, but when I try and run it, I get the error message pictured.
Does anyone know what to do?!
Many thanks
Michael[
![screen shot 2016-08-12 at 23 06 09](https://cloud.githubusercontent.com/assets/20999748/17638375/8cc652a8-60e1-11e6-8750-752f388f9d0e.png)
](url)

**Comment by anttivs** [comment]
My guess is that you are running it under Python 3 and the script was written for Python 2. The parentheses of the print statement are required in Python 3. I should probably fix this, but as I know I am not likely to have time to test changes anytime soon, you could either try running it under Python 2 or to use 2to3 to fix the script (see https://docs.python.org/3.5/library/2to3.html). Or just add parentheses to print statements manually, if that's the only 2to3 issue.

**Comment by MichaelTopple** [comment]
Thank you very much - I'm sorry to be a nuisance. Just to clarify, in order for this to run (assuming I've wired the key correctly), I simply need to execute it in Python 2.x IDLE and hope for the best? Are there other settings I need to tinker with before it will work?

**Comment by anttivs** [comment]
Apart from all the fiddling with connecting the key (straight key only I'm afraid), it should "just work" on a Mac. Please have a look at the INSTALL file which has all the details on connecting the key and if you want to route the audio to fldigi for decoding. If you encounter a problems, just open a ticket and let's see what can be done. I'll close this one for now.
